<a href="https://colab.research.google.com/github/DavidMercadoFaustino/Modelagem-de-Previsao-de-Inadimplencia/blob/main/Explorat%C3%B3ria-Dados/An%C3%A1lise_Explorat%C3%B3ria_de_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# --- Configuração de Caminhos e Carregamento ---
caminho_projeto = '/content/home-credit-default-risk'
imagens_dir = 'imagens'

if not os.path.exists(imagens_dir):
    os.makedirs(imagens_dir)

In [3]:
df=pd.read_csv('df_train_final.csv')

In [4]:
df.head()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY_x,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,credit_card_AMT_DRAWINGS_ATM_CURRENT_MEAN,credit_card_AMT_DRAWINGS_ATM_CURRENT_MAX,credit_card_AMT_DRAWINGS_ATM_CURRENT_MIN,credit_card_AMT_DRAWINGS_CURRENT_MEAN,credit_card_AMT_DRAWINGS_CURRENT_MAX,credit_card_AMT_DRAWINGS_CURRENT_MIN,credit_card_SK_DPD_MEAN,credit_card_SK_DPD_MAX,credit_card_NAME_CONTRACT_STATUS_ACTIVE_SUM,credit_card_NAME_CONTRACT_STATUS_COMPLETED_SUM
0,100002,1,0,202500.0,406597.5,24700.5,351000.0,0.018801,-9461,-637.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,100003,0,0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-16765,-1188.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,0,67500.0,135000.0,6750.0,135000.0,0.010032,-19046,-225.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,0,135000.0,312682.5,29686.5,297000.0,0.008019,-19005,-3039.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0
4,100007,0,0,121500.0,513000.0,21865.5,513000.0,0.028663,-19932,-3038.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df.shape

(307511, 389)

In [6]:
# Selecionar algumas das features criadas para a análise de correlação
features_to_correlate = df.columns
# Ajustar para o caso do merge não encontrar a coluna exata
features_to_correlate = [col for col in features_to_correlate if col in df.columns]

# Calcular a correlação com a variável TARGET
correlation = df[features_to_correlate].corr()['TARGET'].sort_values(ascending=False)

print("\nCorrelação das features com a variável TARGET:")
print(correlation)

Correlação das features com a variável TARGET:
TARGET                     1.000000
DAYS_CREDIT                0.083960
bureau_DAYS_CREDIT_MEAN    0.083960
DAYS_BIRTH                 0.078239
DAYS_ENDDATE_FACT          0.077169
                             ...
YEARS_EMPLOYED            -0.063368
CREDIT_ACTIVE_Closed      -0.076501
EXT_SOURCE_1              -0.079284
EXT_SOURCE_3              -0.155892
EXT_SOURCE_2              -0.160295
Name: TARGET, Length: 389, dtype: float64

In [7]:
strong_correlations = correlation[(correlation > 0.06) | (correlation < -0.06)]

In [8]:
strong_correlations

TARGET                                     1.000000
DAYS_CREDIT                                0.083960
bureau_DAYS_CREDIT_MEAN                    0.083960
DAYS_BIRTH                                 0.078239
DAYS_ENDDATE_FACT                          0.077169
bureau_DAYS_CREDIT_MIN                     0.072869
DAYS_CREDIT_UPDATE                         0.069687
prev_count_NAME_CONTRACT_STATUS_Refused    0.064756
DAYS_EMPLOYED                              0.063368
prev_count_NAME_PRODUCT_TYPE_walk-in       0.062785
REGION_RATING_CLIENT_W_CITY                0.060893
YEARS_EMPLOYED                            -0.063368
CREDIT_ACTIVE_Closed                      -0.076501
EXT_SOURCE_1                              -0.079284
EXT_SOURCE_3                              -0.155892
EXT_SOURCE_2                              -0.160295
Name: TARGET, dtype: float64

In [9]:
# --- Criar o gráfico com subplots ---
plt.style.use('seaborn-v0_8-whitegrid')
fig, axes = plt.subplots(3, 1, figsize=(10, 15))

# Plot para EXT_SOURCE_1
sns.histplot(data=df, x='EXT_SOURCE_1', hue='TARGET',
             ax=axes[0], kde=True, bins=50, palette='viridis',
             multiple='stack', legend=False)
axes[0].set_title('Distribuição de EXT_SOURCE_1 vs. Inadimplência', fontsize=14)
axes[0].set_xlabel('EXT_SOURCE_1')
axes[0].set_ylabel('Contagem')
axes[0].set_xlim(0, 1)

# Plot para EXT_SOURCE_2
sns.histplot(data=df, x='EXT_SOURCE_2', hue='TARGET',
             ax=axes[1], kde=True, bins=50, palette='viridis',
             multiple='stack', legend=False)
axes[1].set_title('Distribuição de EXT_SOURCE_2 vs. Inadimplência', fontsize=14)
axes[1].set_xlabel('EXT_SOURCE_2')
axes[1].set_ylabel('Contagem')
axes[1].set_xlim(0, 1)

# Plot para EXT_SOURCE_3
sns.histplot(data=df, x='EXT_SOURCE_3', hue='TARGET',
             ax=axes[2], kde=True, bins=50, palette='viridis',
             multiple='stack', legend=False)
axes[2].set_title('Distribuição de EXT_SOURCE_3 vs. Inadimplência', fontsize=14)
axes[2].set_xlabel('EXT_SOURCE_3')
axes[2].set_ylabel('Contagem')
axes[2].set_xlim(0, 1)

# Adicionar legenda na figura
handles, labels = axes[0].get_legend_handles_labels()
labels = ['Pago (0)', 'Inadimplente (1)']
fig.legend(handles, labels, loc='upper right', title='Status do Empréstimo', fontsize=12)

plt.tight_layout()

# Salvar o gráfico
plt.savefig(os.path.join(imagens_dir, 'ext_source_distributions.png'))
plt.close()

In [10]:
# Converter DAYS_BIRTH (negativo) para Idade (positivo)
df['AGE_IN_YEARS'] = df['DAYS_BIRTH'] / -365

# Calculate the mean of EXT_SOURCE_2 for each age and target combination
ext_source_2_mean_by_age_target = df.groupby(['AGE_IN_YEARS', 'TARGET'])['EXT_SOURCE_2'].mean().reset_index()

# --- Criar o gráfico de linha ---
plt.style.use('seaborn-v0_8-whitegrid')
plt.figure(figsize=(12, 8))
sns.lineplot(
    x='AGE_IN_YEARS',
    y='EXT_SOURCE_2',
    hue='TARGET',
    data=ext_source_2_mean_by_age_target,
    palette='viridis'
)

plt.title('Relação entre Idade do Cliente e Média do Score EXT_SOURCE_2', fontsize=16)
plt.xlabel('Idade do Cliente (Anos)', fontsize=12)
plt.ylabel('Média do Score EXT_SOURCE_2', fontsize=12)
plt.legend(title='Status do Empréstimo', labels=['Pago (0)', 'Inadimplente (1)'])

# Salvar o gráfico
plt.savefig(os.path.join(imagens_dir, 'age_vs_mean_ext_source_2_line.png'))
plt.close()

In [11]:
# Converter DAYS_BIRTH (negativo) para Idade (positivo)
df['AGE_IN_YEARS'] = df['DAYS_BIRTH'] / -365

# Create age bins of 5 years
bins = range(int(df['AGE_IN_YEARS'].min()), int(df['AGE_IN_YEARS'].max()) + 6, 5)
labels = [f'{i}-{i+4}' for i in bins[:-1]]
df['AGE_BIN'] = pd.cut(df['AGE_IN_YEARS'], bins=bins, labels=labels, right=False, include_lowest=True)

# Calculate the mean of EXT_SOURCE_2 for each age bin and target combination
ext_source_2_mean_by_age_bin_target = df.groupby(['AGE_BIN', 'TARGET'])['EXT_SOURCE_2'].mean().reset_index()

# Convert AGE_BIN to categorical with ordered labels for correct plotting order
ext_source_2_mean_by_age_bin_target['AGE_BIN'] = pd.Categorical(ext_source_2_mean_by_age_bin_target['AGE_BIN'], categories=labels, ordered=True)

# --- Criar o gráfico de linha ---
plt.style.use('seaborn-v0_8-whitegrid')
plt.figure(figsize=(14, 8))
sns.lineplot(
    x='AGE_BIN',
    y='EXT_SOURCE_2',
    hue='TARGET',
    data=ext_source_2_mean_by_age_bin_target,
    palette='viridis'
)

plt.title('Relação entre Faixa Etária do Cliente e Média do Score EXT_SOURCE_2', fontsize=16)
plt.xlabel('Faixa Etária (Anos)', fontsize=12)
plt.ylabel('Média do Score EXT_SOURCE_2', fontsize=12)
plt.legend(title='Status do Empréstimo', labels=['Pago (0)', 'Inadimplente (1)'])
plt.xticks(rotation=45, ha='right') # Rotate x-axis labels for better readability

# Salvar o gráfico
plt.savefig(os.path.join(imagens_dir, 'age_bin_vs_mean_ext_source_2_line.png'))
plt.close()

/tmp/ipython-input-1002699169.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ext_source_2_mean_by_age_bin_target = df.groupby(['AGE_BIN', 'TARGET'])['EXT_SOURCE_2'].mean().reset_index()

In [16]:
# --- Gráfico 1: Renda por Estado Civil vs. Inadimplência ---

plt.style.use('seaborn-v0_8-whitegrid')
plt.figure(figsize=(14, 8))
ax = sns.boxplot(
    x='TARGET',
    y='AMT_INCOME_TOTAL',
    hue='TARGET',
    data=df,
    palette='viridis'
)

# Ajustar a escala do eixo Y para logarítmica
ax.set_yscale('log')

plt.title('Distribuição de Renda vs. Inadimplência', fontsize=16)
plt.xlabel('Inadimplência', fontsize=12)
plt.ylabel('Renda Total (escala logarítmica)', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend(title='Status do Empréstimo', labels=['Pago (0)', 'Inadimplente (1)'])
plt.tight_layout()

# Salvar o gráfico
plt.savefig(os.path.join(imagens_dir, 'income_vs_family_status_boxplot.png'))
plt.close()

In [18]:
plt.style.use('seaborn-v0_8-whitegrid')
plt.figure(figsize=(12, 8))
sns.histplot(
    data=df,
    x='AMT_CREDIT',
    hue='TARGET',
    bins=50,
    kde=True,
    palette='viridis',
    multiple='stack'
)

plt.title('Distribuição do Valor do Empréstimo vs. Inadimplência', fontsize=16)
plt.xlabel('Valor do Empréstimo', fontsize=12)
plt.ylabel('Contagem', fontsize=12)
plt.legend(title='Status do Empréstimo', labels=['Pago (0)', 'Inadimplente (1)'])
plt.tight_layout()

# Salvar o gráfico
plt.savefig(os.path.join(imagens_dir, 'amt_credit_distribution.png'))
plt.close()

In [51]:
# Criamos uma lista com as novas colunas de educação
education_cols = [col for col in df.columns if col.startswith('NAME_EDUCATION_TYPE')]
education_cols.append('TARGET') # Adicionamos a TARGET para agrupar

# Agrupamos por TARGET e calculamos a média para obter a proporção
plot_data = df[education_cols].groupby('TARGET').sum().T.reset_index()

# O reshaping do DataFrame para o gráfico de barras
plot_data.columns = ['Education_Type', 'Pago (0)', 'Inadimplente (1)']
plot_data = plot_data.melt(id_vars='Education_Type', var_name='Target Status', value_name='QTD')
plot_data['porcentagem'] = plot_data['QTD'] / plot_data.groupby('Target Status')['QTD'].transform('sum')

In [52]:
plt.style.use('seaborn-v0_8-whitegrid')
plt.figure(figsize=(14, 8))
ax = sns.barplot(
    x='Education_Type',
    y='porcentagem',
    hue='Target Status',
    data=plot_data,
    palette='viridis'
)

plt.title('Proporção de Clientes por Nível de Educação vs. Inadimplência', fontsize=16)
plt.xlabel('Nível de Educação', fontsize=12)
plt.ylabel('Proporção de Clientes', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend(title='Status do Empréstimo')
plt.tight_layout()

# Salvar o gráfico
plt.savefig(os.path.join(imagens_dir, 'education_vs_target_barplot_post_ohe.png'))
plt.close()

In [53]:
# Criamos uma lista com as novas colunas de educação
family_cols = [col for col in df.columns if col.startswith('NAME_FAMILY_STATUS')]
family_cols.append('TARGET') # Adicionamos a TARGET para agrupar

# Agrupamos por TARGET e calculamos a média para obter a proporção
plot_data = df[family_cols].groupby('TARGET').sum().T.reset_index()

# O reshaping do DataFrame para o gráfico de barras
plot_data.columns = ['FAMILY_STATUS', 'Pago (0)', 'Inadimplente (1)']
plot_data = plot_data.melt(id_vars='FAMILY_STATUS', var_name='Target Status', value_name='QTD')
plot_data['porcentagem'] = plot_data['QTD'] / plot_data.groupby('Target Status')['QTD'].transform('sum')

In [55]:
plt.style.use('seaborn-v0_8-whitegrid')
plt.figure(figsize=(14, 8))
ax = sns.barplot(
    x='FAMILY_STATUS',
    y='porcentagem',
    hue='Target Status',
    data=plot_data,
    palette='viridis'
)

plt.title('Distribuição de Renda por Estado Civil vs. Inadimplência', fontsize=16)
plt.xlabel('Nível de Educação', fontsize=12)
plt.ylabel('Proporção de Clientes', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend(title='Status do Empréstimo')
plt.tight_layout()

# Salvar o gráfico
plt.savefig(os.path.join(imagens_dir, 'family_status_vs_target_barplot_post_ohe.png'))
plt.close()